apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
  namespace: mini-olx
spec:
  type: ClusterIP         # let's expose our service inside the cluster only
  ports:
    - name: db-service
      port: 33061         # it will expose por 33601 targeting to mysql port 3306
      targetPort: 3306
  selector:
    app: db